"""Language detection and bounded multilingual prompts."""

from __future__ import annotations

import re


def detect_language(question: str) -> str:
    # Kept as a fast, deterministic regex (no LLM call) — it only feeds the
    # ``lang`` response field, metrics, and the no-LLM bounded_refusal
    # fallback. The final answer text no longer depends on this: it's
    # generated by the LLM matching the question's language directly (see
    # ``_question_prompt``), because this heuristic is too easily missed by
    # unaccented or unlisted phrasing.
    if re.search(
        r"\b(el|la|los|las|qu[eé]|como|cómo|promedio|cuánt|cuant|estado|"
        r"entrega|puedes|puedo|quiero|necesito|hola|gracias|responder|pregunta)\b",
        question.lower(),
    ):
        return "es"
    return "en"


def _prompt(kind: str, lang: str) -> str:
    language = "Spanish" if lang == "es" else "English"
    return f"Answer in {language}. Use only supplied evidence. Do not fabricate. Task: {kind}."


def _question_prompt(kind: str, question: str) -> str:
    """Build a prompt that asks the LLM to match the question's own language.

    Unlike ``_prompt`` (used for the deterministic ``bounded_refusal``
    fallback, which never calls an LLM), these prompts embed the user's
    actual question and let Gemini detect its language directly — the
    regex-based ``detect_language`` is a fast pre-filter for routing and
    metrics, not reliable enough to dictate the final answer's language.
    """
    return (
        "Detect the language of the user's question below and answer in "
        "that same language. Use only the supplied evidence. Do not "
        f"fabricate.\n\nUser question: {question}\n\nTask: {kind}."
    )


def sql_prompt(question: str) -> str: return _question_prompt("relational answer", question)
def vector_prompt(question: str) -> str: return _question_prompt("semantic answer", question)
def hybrid_prompt(question: str) -> str: return _question_prompt("hybrid answer", question)
def refusal_prompt(lang="en"): return _prompt("bounded refusal", lang)


def bounded_refusal(lang="en"):
    return "No puedo responder con evidencia disponible." if lang == "es" else "I cannot answer that from the available evidence."


def _selftest() -> None:
    assert detect_language("¿Cuál es el promedio?") == "es"
    assert detect_language("Explain the assignment") == "en"
    assert detect_language("que puedes responder ?") == "es"
    assert "Spanish" in refusal_prompt("es")
    prompt = sql_prompt("cuales son mis cursos")
    assert "cuales son mis cursos" in prompt
    assert "Detect the language" in prompt


if __name__ == "__main__":
    _selftest()
