"""``POST /query`` controller (PR 6 task 6.1).

The route is the public surface for the RAG pipeline. It runs the
full tenant dependency chain::

    verify_backend_jwt_dependency → require_tenant → require_tenant_token

so every step is mandatory; skipping any of them raises 401/403
before the route handler runs. The server-derived ``tenant_id`` is
the ONLY source of truth for the query — clients cannot smuggle a
``tenant_id`` through the body because the request schema uses
``extra="forbid"``.

The response shape (PR 6 + design §12.4-12.6) is::

    {answer, lang, route, correlation_id}

The correlation id is a UUID v4 generated by the controller (and
echoed by :class:`app.middleware.correlation_id.CorrelationIdMiddleware`
on the ``X-Correlation-ID`` response header).

When the ``DISABLE_RAG_ROUTES`` feature flag is on, the controller
returns ``503 rag_routes_disabled`` so the operator can hot-disable
the route without redeploying.
"""

from __future__ import annotations

import uuid
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field

from app.core.config import Settings, get_settings
from app.core.deps import require_tenant_token
from app.core.errors import new_correlation_id
from app.core.logging import get_correlation_id, get_logger
from app.observability.metrics import record_rag_request
from app.rag.prompts import detect_language
from app.services.rag_service import RAGService

logger = get_logger("app.controllers.query")

router = APIRouter(prefix="/query", tags=["query"])


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------


class QueryRequest(BaseModel):
    """Inbound payload for ``POST /query``.

    ``extra="forbid"`` blocks clients from passing ``tenant_id`` (or
    any other field) through the body; the Pydantic validator raises
    422 before the route handler runs.
    """

    model_config = ConfigDict(extra="forbid")

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Student's natural-language question.",
    )
    language: str | None = Field(
        default=None,
        max_length=8,
        description="Optional ISO-639-1 override; auto-detected when omitted.",
    )


class QueryResponse(BaseModel):
    """Stable PR 6 response envelope."""

    model_config = ConfigDict(extra="forbid")

    answer: str = Field(..., min_length=1)
    lang: str = Field(..., min_length=2, max_length=8)
    route: str = Field(..., min_length=1)
    correlation_id: str = Field(..., min_length=1, max_length=64)


# ---------------------------------------------------------------------------
# Dependency factories
# ---------------------------------------------------------------------------


def get_rag_service(
    settings: Annotated[Settings, Depends(get_settings)],
) -> RAGService:
    """Return a :class:`RAGService` built from the current settings.

    Tests override this dependency to inject a stub RAG service that
    returns deterministic answers; the production path returns a
    fresh instance per request (the service itself is stateless).
    """
    _ = settings  # placeholder for future wiring (e.g. provider URL)
    return RAGService()


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------


@router.post(
    "",
    response_model=QueryResponse,
    status_code=status.HTTP_200_OK,
)
async def post_query(
    payload: QueryRequest,
    tenant_context: Annotated[tuple[uuid.UUID, str], Depends(require_tenant_token)],
    rag_service: Annotated[RAGService, Depends(get_rag_service)],
    settings: Annotated[Settings, Depends(get_settings)],
) -> QueryResponse:
    """Answer a Canvas-scoped question using the full RAG pipeline.

    The response contract is::

        {answer, lang, route, correlation_id}

    Failures:

    - ``403 tenant_credentials_missing`` when the tenant has no
      decrypted Canvas token (already enforced by the dep chain).
    - ``503 rag_routes_disabled`` when ``DISABLE_RAG_ROUTES`` is on.
    - ``422`` when the request body contains fields outside the
      schema (e.g. a client-supplied ``tenant_id``).
    """
    tenant_id, _canvas_token = tenant_context

    if getattr(settings, "disable_rag_routes", False):
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "code": "rag_routes_disabled",
                "message": "RAG routes are disabled by configuration",
            },
        )

    correlation_id = get_correlation_id() or new_correlation_id()
    language = payload.language or detect_language(payload.question)

    # Refresh provider health so a recent Ollama outage is reflected
    # in the route decision (PR 5 task 5.8 contract).
    rag_service.provider_health()

    try:
        result = rag_service.answer(
            payload.question,
            tenant_id=tenant_id,
            language=language,
        )
    except Exception as exc:  # pragma: no cover - defensive
        logger.exception(
            "rag_answer_failed",
            correlation_id=correlation_id,
            tenant_id=str(tenant_id),
        )
        record_rag_request(route="unknown", lang=language, outcome="error")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "code": "rag_answer_failed",
                "message": "RAG pipeline failed",
            },
        ) from exc

    record_rag_request(
        route=result["route"],
        lang=result["lang"],
        outcome="ok",
    )
    return QueryResponse(
        answer=result["answer"],
        lang=result["lang"],
        route=result["route"],
        correlation_id=correlation_id,
    )


__all__ = [
    "QueryRequest",
    "QueryResponse",
    "get_rag_service",
    "post_query",
    "router",
]


# ---------------------------------------------------------------------------
# Self-test (executable via ``python -m app.controllers.query``)
# ---------------------------------------------------------------------------


def _selftest() -> None:
    """Run end-to-end POST /query assertions with a stub RAG service."""
    import secrets
    import time

    import jwt
    from cryptography.fernet import Fernet
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.core.errors import register_exception_handlers
    from app.middleware.correlation_id import CorrelationIdMiddleware
    from app.security.token_crypto import TokenCipher
    from app.services.tenant_service import (
        TenantRecord,
        TenantService,
        reset_tenant_service,
    )

    reset_tenant_service()
    try:
        import os

        backend_secret = secrets.token_urlsafe(32)
        fernet_key = Fernet.generate_key().decode("ascii")
        os.environ["BACKEND_SECRET"] = backend_secret
        os.environ["TENANT_TOKEN_KEY"] = fernet_key
        os.environ["SUPABASE_DATABASE_URL"] = (
            "postgresql+psycopg://127.0.0.1:1/primer_rag_test"
        )
        os.environ["GEMINI_API_KEY"] = "test-only-gemini"
        os.environ["OLLAMA_HOST"] = "http://127.0.0.1:1"
        os.environ["CANVAS_API_BASE_URL"] = "https://canvas.invalid/api/v1"
        get_settings.cache_clear()

        settings = get_settings()
        cipher = TokenCipher(fernet_key)

        # Seed an in-memory tenant + encrypted credential.
        tenant_service = TenantService()
        tenant = TenantRecord(
            id=uuid.UUID("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
            backend_user_id="user-1",
        )
        tenant_service._tenants_by_id[tenant.id] = tenant
        tenant_service._tenants_by_backend_user["user-1"] = tenant
        tenant_service.store_canvas_token(tenant.id, "plain-canvas-token", cipher)

        import app.services.tenant_service as tenant_module

        tenant_module._default_service = tenant_service

        # Stub RAG service: deterministic answer + language.
        class _StubRAG:
            last_call: dict[str, Any] | None = None

            def provider_health(self) -> dict[str, bool]:
                return {"embedding_available": False}

            def answer(self, question, *, tenant_id, language=None, sql=None):
                _StubRAG.last_call = {
                    "question": question,
                    "tenant_id": tenant_id,
                    "language": language,
                }
                return {
                    "answer": "stub answer",
                    "lang": language or "en",
                    "route": "relational",
                }

        app = FastAPI()
        register_exception_handlers(app)
        app.add_middleware(CorrelationIdMiddleware)
        app.include_router(router)
        app.dependency_overrides[get_rag_service] = lambda: _StubRAG()
        app.dependency_overrides[get_settings] = lambda: settings

        token = jwt.encode(
            {"sub": "user-1", "exp": int(time.time()) + 60},
            backend_secret,
            algorithm="HS256",
        )

        with TestClient(app) as client:
            # 1. Happy path: server-derived tenant + detected language.
            response = client.post(
                "/query",
                headers={"Authorization": f"Bearer {token}"},
                json={"question": "How many assignments?"},
            )
            assert response.status_code == 200, response.text
            body = response.json()
            assert body["answer"] == "stub answer"
            assert body["lang"] == "en"
            assert body["route"] == "relational"
            assert body["correlation_id"]
            assert response.headers.get("X-Correlation-ID") == body["correlation_id"]
            assert _StubRAG.last_call["tenant_id"] == tenant.id

            # 2. Explicit language override.
            response = client.post(
                "/query",
                headers={"Authorization": f"Bearer {token}"},
                json={"question": "¿Cuál es el promedio?", "language": "es"},
            )
            assert response.status_code == 200, response.text
            assert response.json()["lang"] == "es"

            # 3. ``tenant_id`` in the body is rejected by Pydantic.
            response = client.post(
                "/query",
                headers={"Authorization": f"Bearer {token}"},
                json={
                    "question": "hi",
                    "tenant_id": "deadbeef-0000-0000-0000-000000000000",
                },
            )
            assert response.status_code == 422

            # 4. Missing JWT → 401.
            no_auth = client.post("/query", json={"question": "hi"})
            assert no_auth.status_code == 401

            # 5. ``disable_rag_routes`` returns 503.
        disabled_settings = settings.model_copy(
            update={"disable_rag_routes": True}
        )
        app2 = FastAPI()
        register_exception_handlers(app2)
        app2.add_middleware(CorrelationIdMiddleware)
        app2.include_router(router)
        app2.dependency_overrides[get_rag_service] = lambda: _StubRAG()
        app2.dependency_overrides[get_settings] = lambda: disabled_settings

        with TestClient(app2) as client:
            response = client.post(
                "/query",
                headers={"Authorization": f"Bearer {token}"},
                json={"question": "How many assignments?"},
            )
            assert response.status_code == 503
            assert response.json()["code"] == "rag_routes_disabled"
    finally:
        reset_tenant_service()
        get_settings.cache_clear()


if __name__ == "__main__":  # pragma: no cover - manual executable assertion
    _selftest()